from pathlib import Path
import json,hashlib,shutil,subprocess,ctypes as C
w=Path(__file__).resolve().parent;target=w/'numeric_frozen';native=w/'native_numeric_frozen';target.mkdir();native.mkdir();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
old=Path('/scratch/agustin/tmp/gemmini-polynomial-pair-provider-20261006/out/frontier_i64_complete_group/candidate');b=json.loads((old/'build.json').read_text())
for p in old.glob('*.h'):shutil.copyfile(p,target/p.name);shutil.copyfile(p,native/p.name)
shutil.copyfile(old/'provider.c',target/'provider.c');shutil.copyfile(old/'provider.c',native/'provider.c');commands=[]
for cmd in b['compile']:
 cmd=[x.replace(str(old),str(target))for x in cmd];subprocess.run(cmd,check=True);commands.append(cmd)
assert sha(target/'provider.o')==sha(old/'provider.o')
deps=(target/'provider.d').read_text().replace('\\\n',' ').split(':',1)[1].split();pins={str(Path(p).resolve()):sha(Path(p).resolve())for p in deps};pins.update({str(p):sha(p)for p in list(target.glob('*.h'))+[target/'provider.c']});pins[str(Path(commands[0][0]).resolve())]=sha(Path(commands[0][0]).resolve());(target/'reclosure.json').write_text(json.dumps({'compile_commands':commands,'compilation_pins':pins,'compile_cwd':str(Path.cwd()),'object_sha256':sha(target/'provider.o'),'same_qualified_provider_object':True},indent=2)+'\n')
oldn=Path('/scratch/agustin/tmp/gemmini-golden-nofsm-20261004/out/artifacts/probes/smol-soft-floor-composition-20261006/normal_native/numeric_frozen');nm=json.loads((oldn/'manifest.json').read_text());shutil.copyfile(oldn/'numeric_capability.h',native/'numeric_capability.h');shutil.copyfile(oldn/'workspace_frontier_adapter.py',native/'workspace_frontier_adapter.py');cmd=[x.replace(str(oldn),str(native))for x in nm['compile']];subprocess.run(cmd,check=True);nm['compile']=cmd;nm['local_pins']={p.name:sha(p)for p in list(native.glob('*.h'))+[native/'provider.c',native/'provider.so',native/'workspace_frontier_adapter.py']};nm['integer_reconstruction']=True;(native/'manifest.json').write_text(json.dumps(nm,indent=2)+'\n');lib=C.CDLL(str(native/'provider.so'));lib.group_provider_workspace_bytes.restype=C.c_size_t;size=lib.group_provider_workspace_bytes();assert size==121963584+1048576
bridge=w/'bridge';bridge.mkdir();prior=w.parent/'closed_group_endpoint/descriptor_bridge_target';s=(prior/'bridge.c').read_text();assert '121963584'in s;s=s.replace('121963584',str(size));(bridge/'bridge.c').write_text(s)
# Fresh target bridge companion pair and explicit actual ABI before normal link.
base=json.loads((w.parent/'normal_attention_provider_minmax/numeric_frozen/reclosure.json').read_text())['compile_commands'][0];common=base[:base.index('-c')];common=[x.replace(str(w.parent/'normal_attention_provider_minmax/numeric_frozen'),str(target))for x in common]
for ext,flags in [('o',['-c']),('ll',['-S','-emit-llvm'])]:subprocess.run([*common,*flags,str(bridge/'bridge.c'),'-o',str(bridge/('bridge.'+ext))],check=True)
(w/'workspace_contract.json').write_text(json.dumps({'required_bytes':size,'alignment':64,'prior_bytes':121963584,'extra_i64_bytes':1048576,'native_provider_sha256':sha(native/'provider.so'),'query':'actual compiled group_provider_workspace_bytes()','normal_gate':'pending'},indent=2)+'\n');print('WORKSPACE',size)
