from pathlib import Path
import ast,json,subprocess,hashlib,shutil
from mlir_oot.no_fsm_audit import audit_elf
w=Path(__file__).parent.resolve();d=w/'independent_target';d.mkdir(exist_ok=True);core=Path('/scratch/agustin/tmp/merlin-probability-bins-20261006');old=Path('/scratch/agustin/tmp/gemmini-polynomial-pair-provider-20261006/out/word_soft_i64_group')
t=ast.parse((core/'merlin/tests/runtime/test_prepared_bf16_interval.py').read_text());probe=next(ast.literal_eval(n.value)for n in t.body if isinstance(n,ast.Assign)and any(isinstance(a,ast.Name)and a.id=='C'for a in n.targets));probe=probe.replace('FE_TOWARDZERO};','FE_TOWARDZERO,4};').replace('mode<4','mode<5')
s=Path('/scratch/agustin/tmp/gemmini-polynomial-pair-provider-20261006/out/frontier_i64_allocated_pair_v2/driver.c').read_text().replace('int main(void){','int unused_group_main(void){');s+='\n'+probe+'\nint main(void){int status=probe();printf("PREPARED_BINS_FIVE_FRM %d\\n",status);return status;}\n';(d/'proof.c').write_text(s)
c=json.loads((w/'numeric_frozen/compile.json').read_text())['commands'][0];c=[str(d/'proof.c')if x==str(w/'numeric_frozen/provider.c')else str(d/'proof.o')if x==str(w/'numeric_frozen/provider.o')else str(d/'proof.d')if x==str(w/'numeric_frozen/provider.d')else x for x in c];c.insert(1,'-I'+str(Path('/scratch/agustin/tmp/gemmini-polynomial-pair-provider-20261006/out/frontier_i64_allocated_pair_v2')));c.insert(1,'-I/scratch/agustin/tmp/merlin-golden-integration-20261004/merlin/runtime/c');subprocess.run(c,check=True)
link=json.loads((old/'candidate/build.json').read_text())['link'];link=[str(d/'model.elf')if x==str(old/'candidate/model.elf')else str(d/'proof.o')if x.endswith('/frontier_i64_allocated_pair_v2/driver.o')else x for x in link];subprocess.run(link,check=True);a=audit_elf((d/'model.elf').read_bytes());assert a['status']=='pass';(d/'model.nofsm_audit.json').write_text(json.dumps(a,indent=2)+'\n');(d/'build.json').write_text(json.dumps({'compile':c,'link':link},indent=2)+'\n')
with(d/'spike.log').open('w')as f:p=subprocess.Popen(['/scratch2/agustin/chipyard/.conda-env/riscv-tools/bin/spike','--extension=gemmini','--isa=rv64gc','-m0x80000000:0x80000000',str(d/'model.elf')],stdout=f,stderr=subprocess.STDOUT,start_new_session=True)
(d/'process.json').write_text(json.dumps({'pid':p.pid}));print(p.pid)
