"""GENERATED by mlir_oot/tables/gen_funct_table.py from the shipped gemmini.h. Do not hand-edit."""

from __future__ import annotations

#: funct field value for every instruction class the ISA header declares.
FUNCT = {
    'CONFIG': 0,
    'MVIN2': 1,
    'MVIN': 2,
    'MVOUT': 3,
    'COMPUTE_PRELOADED': 4,
    'COMPUTE_ACCUMULATE': 5,
    'PRELOAD': 6,
    'FLUSH': 7,
    'LOOP_WS': 8,
    'LOOP_WS_CONFIG_BOUNDS': 9,
    'LOOP_WS_CONFIG_ADDRS_AB': 10,
    'LOOP_WS_CONFIG_ADDRS_DC': 11,
    'LOOP_WS_CONFIG_STRIDES_AB': 12,
    'LOOP_WS_CONFIG_STRIDES_DC': 13,
    'MVIN3': 14,
    'LOOP_CONV_WS': 15,
    'LOOP_CONV_WS_CONFIG_1': 16,
    'LOOP_CONV_WS_CONFIG_2': 17,
    'LOOP_CONV_WS_CONFIG_3': 18,
    'LOOP_CONV_WS_CONFIG_4': 19,
    'LOOP_CONV_WS_CONFIG_5': 20,
    'LOOP_CONV_WS_CONFIG_6': 21,
    'MVOUT_SPAD': 23,
    'LOOP_WS_CONFIG_SPAD_AB': 24,
    'LOOP_WS_CONFIG_SPAD_C': 25,
    'COUNTER': 126,
}

#: the CONFIG funct's low-2-bit rs1 subtype selector.
CONFIG_SUBTYPE = {
    'EX': 0,
    'LD': 1,
    'ST': 2,
    'BERT': 3,
}

