"""Regenerate ``funct_table.py`` from the shipped gemmini ISA header.

    python mlir_oot/tables/gen_funct_table.py <path-to>/gemmini.h > mlir_oot/tables/funct_table.py

The table is DERIVED, never typed in: the header's ``#define k_<NAME> <N>`` lines are the ISA's own
funct declarations, and the ``CONFIG_<SUBTYPE>`` defines are the low-2-bit subtype selector the
CONFIG funct multiplexes on. Tokenised with ``str.split`` -- this package contains no regular
expressions anywhere (see docs/PLAN.md).
"""

from __future__ import annotations

import sys
from pathlib import Path


def scan(header_text: str) -> tuple[dict[str, int], dict[str, int]]:
    functs: dict[str, int] = {}
    config_subtypes: dict[str, int] = {}
    for line in header_text.splitlines():
        parts = line.split()
        if len(parts) < 3 or parts[0] != "#define":
            continue
        name, value = parts[1], parts[2]
        if not value.isdigit():
            continue
        if name.startswith("k_"):
            functs[name[2:]] = int(value)
        elif name.startswith("CONFIG_") and name != "CONFIG_SCALE_MEM":
            config_subtypes[name[len("CONFIG_"):]] = int(value)
    return functs, config_subtypes


def main(argv: list[str]) -> int:
    header = Path(argv[1]).read_text(errors="ignore")
    functs, subtypes = scan(header)
    out = [
        '"""GENERATED by mlir_oot/tables/gen_funct_table.py from the shipped gemmini.h. Do not hand-edit."""',
        "",
        "from __future__ import annotations",
        "",
        "#: funct field value for every instruction class the ISA header declares.",
        "FUNCT = {",
    ]
    for k in sorted(functs, key=lambda n: functs[n]):
        out.append(f"    {k!r}: {functs[k]},")
    out.append("}")
    out.append("")
    out.append("#: the CONFIG funct's low-2-bit rs1 subtype selector.")
    out.append("CONFIG_SUBTYPE = {")
    for k in sorted(subtypes, key=lambda n: subtypes[n]):
        out.append(f"    {k!r}: {subtypes[k]},")
    out.append("}")
    out.append("")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
