builtin.module {
  func.func @source_quant_frontier(%0: tensor<1x12x1024x64xbf16>) -> (tensor<1x1024x768xi8>, tensor<1x1024xbf16>, tensor<1x1024xbf16>, tensor<1x1024xbf16>) attributes {llvm.emit_c_interface} {
    %1 = tensor.empty() : tensor<1x1024x12x64xbf16>
    %2 = linalg.transpose ins(%0:tensor<1x12x1024x64xbf16>) outs(%1:tensor<1x1024x12x64xbf16>) permutation = [0, 2, 1, 3]
    %3 = tensor.collapse_shape %2 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] {prov.region_id = "view_44", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n1039"], prov.origin_node_ids = ["g:quantized:root:n1874"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn"} : tensor<1x1024x12x64xbf16> into tensor<786432xbf16>
    %4 = tensor.expand_shape %3 [[0 : i64, 1 : i64, 2 : i64]] output_shape [1, 1024, 768] {prov.region_id = "view_44", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n1039"], prov.origin_node_ids = ["g:quantized:root:n1874"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn"} : tensor<786432xbf16> into tensor<1x1024x768xbf16>
    %5 = arith.constant {prov.region_id = "reduce_8", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n1041"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} 0x7f80 : bf16
    %6 = tensor.splat %5 {prov.region_id = "reduce_8", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n1041"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : tensor<1x1024xbf16>
    %7 = "linalg.reduce"(%4, %6) <{dimensions = array<i64: 2>}> ({
    ^bb0(%8: bf16, %9: bf16):
      %10 = "arith.minimumf"(%8, %9) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n1041"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16, bf16) -> bf16
      "linalg.yield"(%10) {prov.source_node_ids = ["g:prepared:root:n1041"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "reduce_8", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n1041"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : (tensor<1x1024x768xbf16>, tensor<1x1024xbf16>) -> tensor<1x1024xbf16>
    %11 = arith.constant {prov.region_id = "reduce_9", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n1042"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} 0xff80 : bf16
    %12 = tensor.splat %11 {prov.region_id = "reduce_9", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n1042"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : tensor<1x1024xbf16>
    %13 = "linalg.reduce"(%4, %12) <{dimensions = array<i64: 2>}> ({
    ^bb1(%14: bf16, %15: bf16):
      %16 = "arith.maximumf"(%14, %15) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n1042"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16, bf16) -> bf16
      "linalg.yield"(%16) {prov.source_node_ids = ["g:prepared:root:n1042"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "reduce_9", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n1042"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : (tensor<1x1024x768xbf16>, tensor<1x1024xbf16>) -> tensor<1x1024xbf16>
    %17 = arith.constant {prov.region_id = "fill_13", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n1043"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} 0.000000e+00 : bf16
    %18 = tensor.empty() : tensor<1x1024xbf16>
    %19 = tensor.splat %17 : tensor<bf16>
    %20 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> ()>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%7, %19 : tensor<1x1024xbf16>, tensor<bf16>) outs(%18 : tensor<1x1024xbf16>) attrs =  {prov.region_id = "minmax_17", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n1044"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.minimum.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb2(%21: bf16, %22: bf16, %23: bf16):
      %24 = arith.minimumf %21, %22 {prov.source_node_ids = ["g:prepared:root:n1044"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%24) {prov.source_node_ids = ["g:prepared:root:n1044"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024xbf16>
    %25 = arith.constant {prov.region_id = "fill_14", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n1045"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} 0.000000e+00 : bf16
    %26 = tensor.empty() : tensor<1x1024xbf16>
    %27 = tensor.splat %25 : tensor<bf16>
    %28 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> ()>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%13, %27 : tensor<1x1024xbf16>, tensor<bf16>) outs(%26 : tensor<1x1024xbf16>) attrs =  {prov.region_id = "minmax_18", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n1046"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.maximum.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb3(%29: bf16, %30: bf16, %31: bf16):
      %32 = arith.maximumf %29, %30 {prov.source_node_ids = ["g:prepared:root:n1046"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%32) {prov.source_node_ids = ["g:prepared:root:n1046"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024xbf16>
    %33 = tensor.empty() : tensor<1x1024xbf16>
    %34 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%20 : tensor<1x1024xbf16>) outs(%33 : tensor<1x1024xbf16>) attrs =  {prov.region_id = "neg_3", prov._pattern_hint = "neg", prov.op = "neg", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1047"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.neg.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb4(%35: bf16, %36: bf16):
      %37 = arith.negf %35 {prov.source_node_ids = ["g:prepared:root:n1047"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%37) {prov.source_node_ids = ["g:prepared:root:n1047"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024xbf16>
    %38 = tensor.empty() : tensor<1x1024xbf16>
    %39 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%34, %28 : tensor<1x1024xbf16>, tensor<1x1024xbf16>) outs(%38 : tensor<1x1024xbf16>) attrs =  {prov.region_id = "minmax_19", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n1048"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.maximum.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb5(%40: bf16, %41: bf16, %42: bf16):
      %43 = arith.maximumf %40, %41 {prov.source_node_ids = ["g:prepared:root:n1048"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%43) {prov.source_node_ids = ["g:prepared:root:n1048"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024xbf16>
    %44 = arith.constant {prov.region_id = "div_3", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} 1.270000e+02 : f32
    %45 = tensor.empty() : tensor<1x1024xf32>
    %46 = tensor.splat %44 : tensor<f32>
    %47 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> ()>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%39, %46 : tensor<1x1024xbf16>, tensor<f32>) outs(%45 : tensor<1x1024xf32>) attrs =  {prov.region_id = "div_3", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb6(%48: bf16, %49: f32, %50: f32):
      %51 = arith.extf %48 {prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : bf16 to f32
      %52 = arith.divf %51, %49 {prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : f32
      "linalg.yield"(%52) {prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (f32) -> ()
    } -> tensor<1x1024xf32>
    %53 = tensor.empty() : tensor<1x1024xbf16>
    %54 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%47 : tensor<1x1024xf32>) outs(%53 : tensor<1x1024xbf16>) attrs =  {prov.region_id = "div_3", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb7(%55: f32, %56: bf16):
      %57 = arith.truncf %55 {prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : f32 to bf16
      "linalg.yield"(%57) {prov.source_node_ids = ["g:prepared:root:n1049"], prov.origin_node_ids = ["g:quantized:root:n1875"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024xbf16>
    %58 = arith.constant {prov.region_id = "fill_15", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n1050"], prov.origin_node_ids = ["g:quantized:root:n1875", "g:quantized:root:n1877"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} 0.000000e+00 : bf16
    %59 = tensor.splat %58 {prov.region_id = "fill_15", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n1050"], prov.origin_node_ids = ["g:quantized:root:n1875", "g:quantized:root:n1877"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : tensor<1x1024xbf16>
    %60 = tensor.empty() : tensor<1x1024xbf16>
    %61 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%54 : tensor<1x1024xbf16>) outs(%60 : tensor<1x1024xbf16>) attrs =  {prov.region_id = "minmax_20", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n1051"], prov.origin_node_ids = ["g:quantized:root:n1875", "g:quantized:root:n1876"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb8(%62: bf16, %63: bf16):
      %64 = arith.constant {prov.source_node_ids = ["g:prepared:root:n1051"], prov.origin_node_ids = ["g:quantized:root:n1875", "g:quantized:root:n1876"], prov.trace_role = "lowering"} 1.001360e-05 : bf16
      %65 = arith.maximumf %62, %64 {prov.source_node_ids = ["g:prepared:root:n1051"], prov.origin_node_ids = ["g:quantized:root:n1875", "g:quantized:root:n1876"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%65) {prov.source_node_ids = ["g:prepared:root:n1051"], prov.origin_node_ids = ["g:quantized:root:n1875", "g:quantized:root:n1876"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024xbf16>
    %66 = tensor.collapse_shape %61 [[0 : i64, 1 : i64]] {prov.region_id = "view_47", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n1053"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : tensor<1x1024xbf16> into tensor<1024xbf16>
    %67 = tensor.expand_shape %66 [[0 : i64, 1 : i64, 2 : i64]] output_shape [1, 1024, 1] {prov.region_id = "view_47", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n1053"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : tensor<1024xbf16> into tensor<1x1024x1xbf16>
    %68 = tensor.collapse_shape %59 [[0 : i64, 1 : i64]] {prov.region_id = "view_48", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n1054"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : tensor<1x1024xbf16> into tensor<1024xbf16>
    %69 = tensor.expand_shape %68 [[0 : i64, 1 : i64, 2 : i64]] output_shape [1, 1024, 1] {prov.region_id = "view_48", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n1054"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} : tensor<1024xbf16> into tensor<1x1024x1xbf16>
    %70 = tensor.empty() : tensor<1x1024x1xbf16>
    %71 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%67 : tensor<1x1024x1xbf16>) outs(%70 : tensor<1x1024x1xbf16>) attrs =  {prov.region_id = "elementwise_5", prov.family = "elementwise", prov._pattern_hint = "elementwise", prov.op = "elementwise", prov.source_node_ids = ["g:prepared:root:n1055"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.reciprocal.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb9(%72: bf16, %73: bf16):
      %74 = arith.constant {prov.source_node_ids = ["g:prepared:root:n1055"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} 1.000000e+00 : bf16
      %75 = arith.divf %74, %72 {prov.source_node_ids = ["g:prepared:root:n1055"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%75) {prov.source_node_ids = ["g:prepared:root:n1055"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024x1xbf16>
    %76 = arith.constant {prov.region_id = "mul_18", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} 1.000000e+00 : f32
    %77 = tensor.empty() : tensor<1x1024x1xf32>
    %78 = tensor.splat %76 : tensor<f32>
    %79 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> ()>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%71, %78 : tensor<1x1024x1xbf16>, tensor<f32>) outs(%77 : tensor<1x1024x1xf32>) attrs =  {prov.region_id = "mul_18", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb10(%80: bf16, %81: f32, %82: f32):
      %83 = arith.extf %80 {prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16 to f32
      %84 = arith.mulf %83, %81 {prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : f32
      "linalg.yield"(%84) {prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (f32) -> ()
    } -> tensor<1x1024x1xf32>
    %85 = tensor.empty() : tensor<1x1024x1xbf16>
    %86 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%79 : tensor<1x1024x1xf32>) outs(%85 : tensor<1x1024x1xbf16>) attrs =  {prov.region_id = "mul_18", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb11(%87: f32, %88: bf16):
      %89 = arith.truncf %87 {prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : f32 to bf16
      "linalg.yield"(%89) {prov.source_node_ids = ["g:prepared:root:n1056"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024x1xbf16>
    %90 = tensor.empty() : tensor<1x1024x768xbf16>
    %91 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%4, %86 : tensor<1x1024x768xbf16>, tensor<1x1024x1xbf16>) outs(%90 : tensor<1x1024x768xbf16>) attrs =  {prov.region_id = "mul_19", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1057"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb12(%92: bf16, %93: bf16, %94: bf16):
      %95 = arith.mulf %92, %93 {prov.source_node_ids = ["g:prepared:root:n1057"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%95) {prov.source_node_ids = ["g:prepared:root:n1057"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024x768xbf16>
    %96 = tensor.empty() : tensor<1x1024x768xbf16>
    %97 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%91 : tensor<1x1024x768xbf16>) outs(%96 : tensor<1x1024x768xbf16>) attrs =  {prov.region_id = "round_3", prov._pattern_hint = "round", prov.op = "round", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1058"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.round.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb13(%98: bf16, %99: bf16):
      %100 = math.roundeven %98 {prov.source_node_ids = ["g:prepared:root:n1058"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%100) {prov.source_node_ids = ["g:prepared:root:n1058"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024x768xbf16>
    %101 = tensor.empty() : tensor<1x1024x768xbf16>
    %102 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%97, %69 : tensor<1x1024x768xbf16>, tensor<1x1024x1xbf16>) outs(%101 : tensor<1x1024x768xbf16>) attrs =  {prov.region_id = "add_9", prov._pattern_hint = "add", prov.op = "add", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n1059"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.add.Tensor", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb14(%103: bf16, %104: bf16, %105: bf16):
      %106 = arith.addf %103, %104 {prov.source_node_ids = ["g:prepared:root:n1059"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%106) {prov.source_node_ids = ["g:prepared:root:n1059"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024x768xbf16>
    %107 = tensor.empty() : tensor<1x1024x768xbf16>
    %108 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%102 : tensor<1x1024x768xbf16>) outs(%107 : tensor<1x1024x768xbf16>) attrs =  {prov.region_id = "minmax_21", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n1060"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "bfloat16", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb15(%109: bf16, %110: bf16):
      %111 = arith.constant {prov.source_node_ids = ["g:prepared:root:n1060"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} -1.270000e+02 : bf16
      %112 = arith.maximumf %109, %111 {prov.source_node_ids = ["g:prepared:root:n1060"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16
      %113 = arith.constant {prov.source_node_ids = ["g:prepared:root:n1060"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} 1.270000e+02 : bf16
      %114 = arith.minimumf %112, %113 {prov.source_node_ids = ["g:prepared:root:n1060"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16
      "linalg.yield"(%114) {prov.source_node_ids = ["g:prepared:root:n1060"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (bf16) -> ()
    } -> tensor<1x1024x768xbf16>
    %115 = tensor.empty() : tensor<1x1024x768xi8>
    %116 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%108 : tensor<1x1024x768xbf16>) outs(%115 : tensor<1x1024x768xi8>) attrs =  {prov.region_id = "dtype_cast_14", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n1062"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "int8", prov.module = "model", prov.fqn = "model.vlm_with_expert.vlm.model.vision_model.encoder.layers.0.self_attn.out_proj"} {
    ^bb16(%117: bf16, %118: i8):
      %119 = arith.fptosi %117 {prov.source_node_ids = ["g:prepared:root:n1062"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : bf16 to i8
      "linalg.yield"(%119) {prov.source_node_ids = ["g:prepared:root:n1062"], prov.origin_node_ids = ["g:quantized:root:n1878"], prov.trace_role = "lowering"} : (i8) -> ()
    } -> tensor<1x1024x768xi8>
    func.return %116, %61, %7, %13 : tensor<1x1024x768xi8>, tensor<1x1024xbf16>, tensor<1x1024xbf16>, tensor<1x1024xbf16>
  }
}