"""Append heldout PC evidence without changing original observation receipts."""
from pathlib import Path
import hashlib,json
R=Path('/scratch/agustin/tmp/gemmini-packed-rhs-current-20261006')
P=R/'out/artifacts/probes/pointwise-dependency-schedule-20261006/div_up_packet_m2'
original=R/'docs/perf_records/tiny_source_exact_division_up_packet_gsim.json'
pc=json.loads((P/'pc_census.json').read_text())
assert pc['records']['baseline']['per_call_classes']==pc['records']['candidate']['per_call_classes']
costs={0:[1601605,1601846],1:[1595754,1595524]}
means={k:sum(v)/len(v) for k,v in costs.items()}
pins={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in [original,P/'pc_census.json',P/'disassembly.txt',P/'symbols.txt',P/'histogram.stdout',P/'histogram.stderr',P/'build/layer.elf',P/'qualification.json',P/'gsim_receipt.json',P/'gsim.stdout',R/'out/artifacts/probes/pointwise-dependency-schedule-20261006/packet_numeric/receipt.json',Path(__file__),R/'out/artifacts/probes/source-expression-interval-table-20261006/holdout_div_up_pc_census.py']}
record={'schema':'tiny_source_exact_ordering_heldout_pc_adjunct_v1','original_receipt_unchanged':{'path':str(original),'sha256':pins[str(original)],'original_commit':'c95f78c'},'hypothesis':'Operation counts alone may miss actual dependency ordering and overlap even for source-exact arithmetic. This records a complete-source heldout pair; no ranking is approved.','ownership':{'generic_source_independence_numeric_proof':'Merlin generated probe','actual_CPU_instruction_packet_earlyclobber_and_disassembly':'OOT'},'actual_change':'Same original scalar operations, source chains and all numerical words/flags, mixed DIV and independent up cast/multiply order only. No workload/provenance strategy selector.','scope':'Complete original current2004 first pre-down M2/full5632 columns, original11264 i8, shared addresses/inputhashes/guards; not whole model or stock FireSim.','raw_gsim_ABBA':[{'index':i,'arm':a,'cycles':c} for i,a,c in [(0,0,1601605),(1,1,1595754),(2,1,1595524),(3,0,1601846)]],'sample_means':{'control_cycles':means[0],'candidate_cycles':means[1],'absolute_delta_cycles':means[0]-means[1],'nominal_candidate_fraction_change':means[1]/means[0]-1},'observed_ABBA_range':{'control_cycles':max(costs[0])-min(costs[0]),'candidate_cycles':max(costs[1])-min(costs[1]),'control_range_over_mean':(max(costs[0])-min(costs[0]))/means[0],'candidate_range_over_mean':(max(costs[1])-min(costs[1]))/means[1],'interpretation':'Only two samples per arm; observed ranges are not statistical confidence intervals. Nominal small difference may be within broader timing noise/context variation. No approved ranking or promotion.'},'equal_feature_point_floor':{'absolute_delta_over_sum':abs(means[0]-means[1])/(means[0]+means[1]),'interpretation':'If these two point labels are treated as exact and model emits one identical prediction from equal counted features, minimum worst relative point error is abs(delta)/(sum). This is not a measured uncertainty bound or unavoidable true hardware model error.'},'actual_PC_execution':{'both_body_instructions_per_call':568958,'calls_per_arm':3,'all_dynamic_opcode_and_class_counts_equal':True,'classes_per_call':pc['records']['baseline']['per_call_classes'],'CSR_scope':'Both source helper bodies CSR-free; raw Spike-g dispatch counts, no cycles/latencies inferred. Serialized CSR retry artifacts excluded.'},'gates':'Original native/strict11264,guards/inputhashes,zeroFSM; source100200 paired total tests across5FRM/all32sticky flags already sealed; no new numeric or timing rerun. Same-ELF-g histogram only.','result':'HELD, no production transform or whole/stock admission. Use as weak heldout scheduling/context case and require emitted dependency/liveness/caller composition before predicting changes.','tokens':{'token_usage_available':False,'scope':'Root owns shared campaign checkpoints; exclusive per-agent/per-experiment allocation unavailable'},'pins':pins}
target=R/'docs/perf_records/tiny_source_exact_ordering_heldout_pc_adjunct.json'
assert not target.exists();target.write_text(json.dumps(record,indent=2)+'\n')
print('HELDOUT_PC_ADJUNCT_ARCHIVED',len(pins),flush=True)
